name: Esquina
favicon: null
layout_spectrum: 0.82149
typography_spectrum: 0.45601
title: 'Esquina: Conversas sobre Cidades e Arquitetura'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a01f62'
    - '#fefefe'
    - '#916c90'
    - '#82d1cc'
    - '#f162a2'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
