name: Esquina
favicon: null
layout_spectrum: 0.88748
typography_spectrum: 0.00254
title: 'Esquina: Conversas sobre Cidades e Arquitetura'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a01f62'
    - '#fefefe'
    - '#916c90'
    - '#82d1cc'
    - '#f162a2'
  brandStrength: 0.5546936742030084
  lightness: 0.9466419357340783
  saturation: 0.10764519171789289
  rhythmicContrast: 0.08741609007120132
purpose: []
